<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonHocTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['name' => 'VIE1026_Pháp luật', 'bo_mon_id' => 1],
            ['name' => 'SKI2015_Kỹ năng làm việc', 'bo_mon_id' => 1],
            ['name' => 'VIE1016_Chính trị', 'bo_mon_id' => 1],
            ['name' => 'SKI1014_Kỹ năng học tập', 'bo_mon_id' => 1],
            ['name' => 'PRE103_Kỹ năng sáng tạo', 'bo_mon_id' => 1],
            ['name' => 'VIE103_Giáo dục thể chất - Vovinam 1', 'bo_mon_id' => 1],
            ['name' => 'COM1071_Tin học', 'bo_mon_id' => 2],
            ['name' => 'COM1014_Tin học cơ sở', 'bo_mon_id' => 2],
            ['name' => 'COM2012_Cơ sở dữ liệu', 'bo_mon_id' => 2],
            ['name' => 'COM2012_Cơ sở dữ liệu', 'bo_mon_id' => 2],
            ['name' => 'MOB104_Quản lý dự án với phần mềm Agile', 'bo_mon_id' => 2],
            ['name' => 'MOB202_Thiết kế giao diện trên Android', 'bo_mon_id' => 2],
            ['name' => 'MOB401_Lập trình game 2D nâng cao', 'bo_mon_id' => 2],
            ['name' => 'MOB402_Lập trình server cho Android', 'bo_mon_id' => 2],
            ['name' => 'MOB403_Android Networking', 'bo_mon_id' => 2],
            ['name' => 'PRO1014_Dự án 1 (TKTW)', 'bo_mon_id' => 2],
            ['name' => 'PRO1121_Dự án 1 (LTMT)', 'bo_mon_id' => 2],
            ['name' => 'WEB1013_Xây dựng trang Web', 'bo_mon_id' => 2],
            ['name' => 'WEB1043_Lập trình cơ sở với JavaScript', 'bo_mon_id' => 2],
            ['name' => 'WEB2014_Lập trình PHP 1', 'bo_mon_id' => 2],
            ['name' => 'WEB3023_Thiết kế Web với HTML5&CSS3', 'bo_mon_id' => 2],
            ['name' => 'WEB207_Front-End Frameworks', 'bo_mon_id' => 2],
            ['name' => 'WEB209_Lập trình Front-End Framework 2', 'bo_mon_id' => 2],
            ['name' => 'WEB3014_Lập trình PHP 2', 'bo_mon_id' => 2],
            ['name' => 'WEB4013_Lập trình PHP 3', 'bo_mon_id' => 2],
            ['name' => 'WEB502_Lập trình TypeScript', 'bo_mon_id' => 2],
            ['name' => 'WEB503_NodeJS & Restful Web Service', 'bo_mon_id' => 2],
            ['name' => 'MUL1013_Thiết kế hình ảnh với Photoshop', 'bo_mon_id' => 3],
            ['name' => 'MUL1143_Luật xa gần và bố cục trong thiết kế đồ họa', 'bo_mon_id' => 3],
            ['name' => 'MUL116_Nhập môn đồ họa', 'bo_mon_id' => 3],
            ['name' => 'MUL117_Kỹ thuật nhiếp ảnh', 'bo_mon_id' => 3],
            ['name' => 'MUL2111_Chế bản điện tử với InDesign', 'bo_mon_id' => 3],
            ['name' => 'MUL2123_Thiết kế bao bì', 'bo_mon_id' => 3],
            ['name' => 'MUL2133_Nghệ thuật chữ', 'bo_mon_id' => 3],
            ['name' => 'MUL217_Ý tưởng sáng tạo', 'bo_mon_id' => 3],
            ['name' => 'MUL220_Xử lý phim với Adobe Premiere', 'bo_mon_id' => 3],
            ['name' => 'MUL2211_Thiết kế phối cảnh nội thất với 3D Max', 'bo_mon_id' => 3],
            ['name' => 'MUL222_Dựng hình với Maya 3D', 'bo_mon_id' => 3],
            ['name' => 'MUL311_Thiết kế đồ họa động với 3D Studio Max', 'bo_mon_id' => 3],
            ['name' => 'MUL318_Cinema 4D', 'bo_mon_id' => 3],
            ['name' => 'MUL320_Thiết kế tạo hình nhân vật Maya 3D', 'bo_mon_id' => 3],
            ['name' => 'MUL3211_Hiệu ứng kỹ xảo với Adobe After Effect', 'bo_mon_id' => 3],
            ['name' => 'MUL322_Dựng phối cảnh với SketchUp', 'bo_mon_id' => 3],
            ['name' => 'PRO1112_Dự án 1 (TKĐH)', 'bo_mon_id' => 3],
            ['name' => 'BUS2051_Quản trị dự án kinh doanh', 'bo_mon_id' => 4],
            ['name' => 'DOM106_Hành vi khách hàng', 'bo_mon_id' => 4],
            ['name' => 'MAR1021_Marketing căn bản', 'bo_mon_id' => 4],
            ['name' => 'MAR103_Nhập môn Marketing và bán hàng', 'bo_mon_id' => 4],
            ['name' => 'MAR2023_Nghiên cứu Marketing', 'bo_mon_id' => 4],
            ['name' => 'MAR206_Quảng cáo', 'bo_mon_id' => 4],
            ['name' => 'MAR2071_Truyền thông Marketing tích hợp', 'bo_mon_id' => 4],
            ['name' => 'PRE101_Nhập môn Quan hệ công chúng', 'bo_mon_id' => 4],
            ['name' => 'PRE104_Kỹ năng hoạt náo', 'bo_mon_id' => 4],
            ['name' => 'PRE1051_Truyền thông đa phương tiện', 'bo_mon_id' => 4],
            ['name' => 'PRE106_Kỹ năng đàm phán', 'bo_mon_id' => 4],
            ['name' => 'PRE201_Quan hệ công chúng', 'bo_mon_id' => 4],
            ['name' => 'PRE2021_PR nội bộ và PR cộng đồng', 'bo_mon_id' => 4],
            ['name' => 'PRE208_Xây dựng và phát triển thương hiệu', 'bo_mon_id' => 4],
            ['name' => 'PRE210_Nghiệp vụ tổ chức sự kiện', 'bo_mon_id' => 4],
            ['name' => 'PRO1024_Dự án 1 (QTDNVVN)', 'bo_mon_id' => 4],
            ['name' => 'PRO1141_Dự án 1 (QHCC)', 'bo_mon_id' => 4],
            ['name' => 'SYB3011_Khởi sự doanh nghiệp', 'bo_mon_id' => 4],
            ['name' => 'ACC105_Kế toán khách sạn nhà hàng', 'bo_mon_id' => 5],
            ['name' => 'EHO102_Tiếng anh chuyên ngành 1 (NHKS)', 'bo_mon_id' => 5],
            ['name' => 'EHO202_Tiếng anh chuyên ngành 2 (NHKS)', 'bo_mon_id' => 5],
            ['name' => 'ETO101_Tiếng Anh chuyên ngành 1 (HDDL)', 'bo_mon_id' => 5],
            ['name' => 'HIS1011_Cơ sở văn hóa Việt Nam', 'bo_mon_id' => 5],
            ['name' => 'HOS1011_Nghiệp vụ lễ tân', 'bo_mon_id' => 5],
            ['name' => 'HOS1021_Thực hành nghiệp vụ lễ tân', 'bo_mon_id' => 5],
            ['name' => 'HOS1041_Thực hành nghiệp vụ nhà hàng', 'bo_mon_id' => 5],
            ['name' => 'HOS2021_Thực hành nghiệp vụ lưu trú', 'bo_mon_id' => 5],
            ['name' => 'HOS305_Thực hành nghiệp vụ nhà hàng nâng cao', 'bo_mon_id' => 5],
            ['name' => 'HOS401_Quản trị khách sạn', 'bo_mon_id' => 5],
            ['name' => 'HOS4021_Quản trị các dịch vụ giải trí trong khách sạn', 'bo_mon_id' => 5],
            ['name' => 'HOS4031_Quản trị chất lượng dịch vụ', 'bo_mon_id' => 5],
            ['name' => 'TOU2013_Nghiệp vụ tổ chức sự kiện', 'bo_mon_id' => 5],
            ['name' => 'TOU4021_Điều hành chương trình du lịch', 'bo_mon_id' => 5],
            ['name' => 'AUT102_Mạch điện và an toàn điện', 'bo_mon_id' => 6],
            ['name' => 'AUT103_Điện tử cơ bản', 'bo_mon_id' => 6],
            ['name' => 'AUT106_Mạch điện tử và ứng dụng', 'bo_mon_id' => 6],
            ['name' => 'AUT107_Lắp đặt hệ thống điện', 'bo_mon_id' => 6],
            ['name' => 'AUT109_Lý thuyết điều khiển tự động', 'bo_mon_id' => 6],
            ['name' => 'AUT110_Kỹ thuật cảm biến', 'bo_mon_id' => 6],
            ['name' => 'AUT214_Tự động hóa quá trình công nghệ', 'bo_mon_id' => 6],
            ['name' => 'INE115_Điện tử công suất', 'bo_mon_id' => 6],
            ['name' => 'INE202_Truyền động điện', 'bo_mon_id' => 6],
            ['name' => 'INE218_Phát triển ứng dụng của IOT', 'bo_mon_id' => 6],
            ['name' => 'INE221_Tự động hóa trong sản xuất', 'bo_mon_id' => 6],
            ['name' => 'INE222_Vẽ thiết kế điện', 'bo_mon_id' => 6],
            ['name' => 'PRO125_Dự án 1 (TĐH)', 'bo_mon_id' => 6],
            ['name' => 'MEC214_Nguyên lý cắt', 'bo_mon_id' => 6],
            ['name' => 'MEC211_Gia công tia lửa điện', 'bo_mon_id' => 6],
            ['name' => 'MEC212_Thực hành Phay - Tiện CNC', 'bo_mon_id' => 6],
            ['name' => 'MEC215_Vẽ và thiết kế trên máy tính', 'bo_mon_id' => 6],
            ['name' => 'MEC219_Thực hành cắt gọt kim loại', 'bo_mon_id' => 6],
            ['name' => 'DOM1021_Email Marketing', 'bo_mon_id' => 7],
            ['name' => 'DOM1031_Marketing nội dung', 'bo_mon_id' => 7],
            ['name' => 'DOM104_Công cụ tiện ích', 'bo_mon_id' => 7],
            ['name' => 'DOM105_Marketing mạng xã hội', 'bo_mon_id' => 7],
            ['name' => 'DOM107_SEO & Marketing trên công cụ tìm kiếm', 'bo_mon_id' => 7],
            ['name' => 'DOM202_Hoạch định chiến lược Marketing số', 'bo_mon_id' => 7],
            ['name' => 'DOM203_Kỹ thuật phân tích và tổng hợp', 'bo_mon_id' => 7],
            ['name' => 'PRO1131_Dự án 1 (TMĐT)', 'bo_mon_id' => 7],
            ['name' => 'MOB1014_Lập trình Java 1', 'bo_mon_id' => 8],
            ['name' => 'MOB1023_Lập trình Java 2', 'bo_mon_id' => 8],
            ['name' => 'NET101_Lập trình C#1', 'bo_mon_id' => 8],
            ['name' => 'NET103_Lập trình C#3', 'bo_mon_id' => 8],
            ['name' => 'NET104_Lập trình C#4', 'bo_mon_id' => 8],
            ['name' => 'NET106_Lập trình C#6', 'bo_mon_id' => 8],
            ['name' => 'PRO1041_Dự án 1 (UDPM-Java)', 'bo_mon_id' => 8],
            ['name' => 'PRO131_Dự án 1 (UDPM-.NET)', 'bo_mon_id' => 8],
            ['name' => 'SOF203_Lập trình Java 3', 'bo_mon_id' => 8],
            ['name' => 'SOF3011_Lập trình Java 4', 'bo_mon_id' => 8],
            ['name' => 'SOF3021_Lập trình Java 5', 'bo_mon_id' => 8],
            ['name' => 'SOF306_Lập trình Java 6', 'bo_mon_id' => 8],
            ['name' => 'SOF3031_Kiểm thử cơ bản', 'bo_mon_id' => 8],
            ['name' => 'SOF307_Cấu trúc dữ liệu và giải thuật', 'bo_mon_id' => 8],
        ];
        DB::table('mon_hoc')->insert($data);

    }
}
